version: "3.9"
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github-pipedrive-api
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nodejs:
    image: node:8.11.1-alpine
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000
    